version: "3.9"

services:
  server:
    container_name: server
    build: ./server
    environment:
      - IPSTACK_API_KEY=http://api.ipstack.com/190.251.146.218?access_key=4a9355295da7ed5babd11364dbbd328e
    ports:
      - 4001:4001
  
  spa:
    container_name: spa
    build: ./spa
    ports: 
      - 5000:5001
    environment:
      - VUE_APP_API_ENDPOINT=http://backend:4001/api


  